apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bert-cpu.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bert-cpu.name" . }}
    helm.sh/chart: {{ include "bert-cpu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bert-cpu.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bert-cpu.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NUM_WORKER
              value: {{ .Values.envVar.numWorker | quote }}
            - name: MAX_BATCH_SIZE
              value: {{ .Values.envVar.maxBatchSize | quote}}
            - name: MAX_SEQ_LEN
              value: {{ .Values.envVar.maxSeqLen | quote}}
          ports:
            - name: bport
              containerPort: 5555
              protocol: TCP
            - name: bportout
              containerPort: 5556
              protocol: TCP
            - name: http
              containerPort: 8125
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
