apiVersion: v1
kind: Service
metadata:
  name: {{ include "bert-cpu.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bert-cpu.name" . }}
    helm.sh/chart: {{ include "bert-cpu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.bport }}
      targetPort: bport
      protocol: TCP
      name: bport
    - port: {{ .Values.service.bportout }}
      targetPort: bportout
      protocol: TCP
      name: bportout
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "bert-cpu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
